import { GoogleGenAI } from '@google/genai';
import { Project, Inspection } from '../types';

let aiClient: GoogleGenAI | null = null;

function getAIClient(): GoogleGenAI | null {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey || apiKey === 'MY_GEMINI_API_KEY') {
    return null;
  }
  if (!aiClient) {
    aiClient = new GoogleGenAI({ apiKey });
  }
  return aiClient;
}

export interface AIAnalysisResult {
  isSimulatedFallback: boolean;
  modelUsed: string;
  riskSummary: string;
  possibleAnomalies: string[];
  attendanceConcerns: string[];
  inspectionConcerns: string[];
  recommendedFollowUpActions: string[];
  calculatedConfidenceScore: number;
  disclaimer: string;
}

export async function analyzeProjectWithGemini(
  project: Project,
  recentInspections: Inspection[],
  recentAttendanceNotes?: string[]
): Promise<AIAnalysisResult> {
  const disclaimer =
    'AI NOTICE: This assessment is an automated anomaly alert and risk indicator for monitoring prioritization. It does not constitute proof of irregularity or wrongdoing.';

  const ai = getAIClient();

  // If Gemini API key is missing, return a thoughtful heuristic analysis with simulation flag
  if (!ai) {
    return generateLocalRiskAssessment(project, recentInspections, disclaimer);
  }

  try {
    const prompt = `
You are the Senior Government AI Risk Analyst for India's Ministry of Social Justice and Empowerment (DoSJE).
Analyze the following project monitoring telemetry and return a structured JSON assessment.

PROJECT TELEMETRY:
- Project Name: ${project.projectName}
- Scheme: ${project.scheme}
- NGO: ${project.ngoName}
- Location: ${project.district}, ${project.state}
- Beneficiaries Count: ${project.beneficiaryCount}
- Staff Count: ${project.staffCount}
- CCTV Status: ${project.cctvStatus} (Active: ${project.activeCamerasCount}/${project.totalCamerasCount})
- Average Attendance: ${project.averageAttendancePercent}% (Status: ${project.attendanceStatus})
- Existing Risk Score: ${project.riskScore}/100 (${project.riskLevel})
- Risk Breakdown Notes: ${project.riskBreakdown?.notes?.join('; ') || 'None'}
- Recent Attendance Notes: ${recentAttendanceNotes?.join('; ') || 'None'}
- Recent Inspection History:
${recentInspections
  .map(
    (i) =>
      `  * Date: ${i.scheduledDate}, Result: ${i.overallResult || 'Pending'}, GPS Status: ${
        i.gps?.status || 'N/A'
      }, Findings: ${i.findings || 'Pending'}`
  )
  .join('\n') || '  * No prior inspections recorded'}

STRICT GUIDELINES:
1. Treat all outputs as potential indicators, alerts, or recommendations for inspection scheduling.
2. NEVER use definitive accusatory wording like "fraud confirmed" or "criminal misuse". Use conservative, objective government terminology such as "Potential anomaly detected", "Discrepancy warrants field verification", "Elevated monitoring advised".
3. Return STRICTLY VALID JSON without any markdown ticks or surrounding text.

Required JSON Structure:
{
  "riskSummary": "Concise 2-sentence executive summary of monitoring posture",
  "possibleAnomalies": ["list of potential anomalies or risk vectors"],
  "attendanceConcerns": ["attendance-specific concerns"],
  "inspectionConcerns": ["inspection, CCTV or location-specific concerns"],
  "recommendedFollowUpActions": ["actionable recommendations for department officers"],
  "calculatedConfidenceScore": 85
}
`;

    const response = await ai.models.generateContent({
      model: 'gemini-3.8-flash',
      contents: prompt,
      config: {
        responseMimeType: 'application/json',
      },
    });

    const text = response.text || '';
    const parsed = JSON.parse(text);

    return {
      isSimulatedFallback: false,
      modelUsed: 'gemini-3.8-flash',
      riskSummary: parsed.riskSummary || 'Monitoring assessment generated by Gemini.',
      possibleAnomalies: parsed.possibleAnomalies || [],
      attendanceConcerns: parsed.attendanceConcerns || [],
      inspectionConcerns: parsed.inspectionConcerns || [],
      recommendedFollowUpActions: parsed.recommendedFollowUpActions || [],
      calculatedConfidenceScore: parsed.calculatedConfidenceScore || 85,
      disclaimer,
    };
  } catch (error) {
    console.warn('Gemini API call failed or timed out, falling back gracefully:', error);
    return generateLocalRiskAssessment(project, recentInspections, disclaimer);
  }
}

export async function summarizeInspectionWithGemini(
  inspection: Inspection
): Promise<{ summary: string; followUps: string[]; isSimulated: boolean }> {
  const ai = getAIClient();

  if (!ai) {
    return {
      summary: `Automated summary: Inspection ${inspection.inspectionCode} for ${inspection.projectName} resulted in ${
        inspection.overallResult || 'PENDING'
      }. GPS verification was ${inspection.gps?.status || 'COMPLETED'}. Checklist identified ${
        inspection.checklist.filter((c) => c.status === 'FAIL').length
      } non-compliant areas.`,
      followUps: [
        'Issue verification receipt to project incharge.',
        'Review biometric discrepancies in next quarterly review.',
      ],
      isSimulated: true,
    };
  }

  try {
    const prompt = `
Summarize this DoSJE official inspection report in 2 professional sentences and suggest 3 follow-up administrative actions.
Project: ${inspection.projectName} (${inspection.scheme})
Inspector: ${inspection.inspectorName}
Result: ${inspection.overallResult}
GPS: ${inspection.gps?.status} (distance: ${inspection.gps?.distanceFromProjectMeters}m)
Checklist observations:
${inspection.checklist.map((c) => `- ${c.title}: ${c.status} (${c.observations})`).join('\n')}
Findings: ${inspection.findings}
Remarks: ${inspection.remarks}

Return JSON strictly:
{
  "summary": "...",
  "followUps": ["action 1", "action 2", "action 3"]
}
`;
    const response = await ai.models.generateContent({
      model: 'gemini-3.8-flash',
      contents: prompt,
      config: {
        responseMimeType: 'application/json',
      },
    });

    const parsed = JSON.parse(response.text || '{}');
    return {
      summary: parsed.summary || 'Inspection summarized.',
      followUps: parsed.followUps || [],
      isSimulated: false,
    };
  } catch (err) {
    console.warn('Gemini inspection summary failed, using fallback:', err);
    return {
      summary: `Inspection ${inspection.inspectionCode} recorded with status ${inspection.overallResult}.`,
      followUps: ['Review checklist observations with district authority.'],
      isSimulated: true,
    };
  }
}

function generateLocalRiskAssessment(
  project: Project,
  recentInspections: Inspection[],
  disclaimer: string
): AIAnalysisResult {
  const anomalies: string[] = [];
  const attConcerns: string[] = [];
  const inspConcerns: string[] = [];
  const actions: string[] = [];

  if (project.cctvStatus === 'OFFLINE') {
    anomalies.push('Extended CCTV stream outage detected (>48 hours uninterrupted).');
    inspConcerns.push('Camera feed unavailable for live visual confirmation of activity.');
    actions.push('Issue urgent technical compliance notice for immediate CCTV reboot and RTSP ping verification.');
  } else if (project.cctvStatus === 'WARNING') {
    inspConcerns.push('Intermittent frame drops or low resolution reported on secondary cameras.');
  }

  if (project.averageAttendancePercent < 60) {
    anomalies.push(`Significant attendance deviation: reported average ${project.averageAttendancePercent}% vs sanctioned rolls.`);
    attConcerns.push('Potential non-operational periods or unrecorded absenteeism in beneficiary cohorts.');
    actions.push('Schedule surprise physical verification of daily meal registers and attendance logs.');
  } else if (project.attendanceStatus === 'WARNING') {
    attConcerns.push('Minor discrepancies between biometric records and physical check-in rosters.');
  }

  const failedInspections = recentInspections.filter((i) => i.overallResult === 'NON_COMPLIANT');
  if (failedInspections.length > 0) {
    anomalies.push(`Prior non-compliance flag on record (${failedInspections[0].inspectionCode}).`);
    inspConcerns.push('Past deficiencies in staffing or infrastructure yet to be verified as resolved.');
    actions.push('Convene district evaluation committee to review remediation status.');
  }

  if (anomalies.length === 0) {
    anomalies.push('No severe anomalies detected at present. Standard operational baseline observed.');
    actions.push('Maintain regular quarterly inspection schedule.');
  }

  const riskSummary =
    project.riskScore >= 70
      ? `High monitoring priority project due to combined indicators: ${anomalies.join(' ')}`
      : project.riskScore >= 40
      ? `Moderate risk index (${project.riskScore}/100). Telemetry indicates stable activity with isolated advisory points.`
      : `Low risk project (${project.riskScore}/100). Operations, attendance (${project.averageAttendancePercent}%), and CCTV streaming align with department guidelines.`;

  return {
    isSimulatedFallback: true,
    modelUsed: 'Heuristic Rule Engine (Gemini API key inactive or pending configuration)',
    riskSummary,
    possibleAnomalies: anomalies,
    attendanceConcerns: attConcerns.length > 0 ? attConcerns : ['No critical attendance concerns flagged.'],
    inspectionConcerns: inspConcerns.length > 0 ? inspConcerns : ['All cameras and physical markers within nominal limits.'],
    recommendedFollowUpActions: actions,
    calculatedConfidenceScore: project.riskScore >= 70 ? 91 : 84,
    disclaimer,
  };
}
