import json
import os

with open('src/i18n/extracted_existing.json', 'r', encoding='utf-8') as f:
    existing = json.load(f)

with open('scripts/base_en.json', 'r', encoding='utf-8') as f:
    en_dict = json.load(f)

with open('scripts/base_hi.json', 'r', encoding='utf-8') as f:
    hi_dict = json.load(f)

def write_ts_file(lang_code, lang_name, lang_dict):
    out_path = f"src/i18n/translations/{lang_code}.ts"
    lines = [
        f"// Translation dictionary for {lang_name} ({lang_code})",
        f"export const {lang_code}: Record<string, string> = {{"
    ]
    for k in sorted(en_dict.keys()):
        v = lang_dict.get(k)
        if not v:
            v = hi_dict.get(k, en_dict[k])
        escaped_v = str(v).replace('\\', '\\\\').replace("'", "\\'").replace('\n', '\\n')
        lines.append(f"  '{k}': '{escaped_v}',")
    lines.append("};")
    lines.append(f"export default {lang_code};")
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')
    print(f"Wrote {out_path} with {len(en_dict)} keys")

# Telugu additions
te_extra = {
  'hero.badge': 'భారత ప్రభుత్వం • సామాజిక న్యాయం మరియు సాధికారత మంత్రిత్వ శాఖ',
  'hero.title': 'సత్య నిరీక్షక్ · జాతీయ సంస్థాగత నిఘా మరియు తనిఖీ కమాండ్ గ్రిడ్',
  'hero.dept': 'సామాజిక న్యాయం మరియు సాధికారత విభాగం (DoSJE)',
  'hero.desc': 'దేశవ్యాప్తంగా గ్రాంట్-ఇన్-ఎయిడ్ వృద్ధాశ్రమాలు, డి-అడిక్షన్ కేంద్రాలు మరియు పునరావాస సంస్థలలో 24×7 ప్రత్యక్ష సీసీటీవీ పర్యవేక్షణ, బయోమెట్రిక్ హాజరు మరియు ఆన్-సైట్ తనిఖీల కోసం కేంద్రీకృత డిజిటల్ పోర్టల్.',
  'hero.super_admin_title': 'సూపర్ అడ్మిన్',
  'hero.super_admin_desc': 'పూర్తి జాతీయ గ్రిడ్ నియంత్రణ, వినియోగదారు పాత్రలు & ఆడిట్ కన్సోల్',
  'hero.super_admin_login': 'సూపర్ అడ్మిన్‌గా లాగిన్ అవ్వండి',
  'hero.inspector_title': 'తనిఖీ అధికారులు',
  'hero.inspector_desc': 'ఆకస్మిక వీడియో కాల్స్, గ్రౌండ్ సాక్ష్యాలు మరియు తనిఖీ నివేదికలు',
  'hero.inspector_login': 'ఇన్‌స్పెక్టర్‌గా లాగిన్ అవ్వండి',
  'hero.district_title': 'జిల్లా సంక్షేమ అధికారులు',
  'hero.district_desc': 'ప్రాంతీయ వ్యత్యాసాల సమీక్షలు మరియు నిధుల ధృవీకరణ',
  'hero.district_login': 'అథారిటీగా లాగిన్ అవ్వండి',
  'hero.ministry_title': 'కేంద్ర మంత్రిత్వ శాఖ',
  'hero.ministry_desc': 'జాతీయ ఆడిట్, బడ్జెట్ మరియు కాగ్ క్లియరెన్స్',
  'hero.ministry_login': 'మంత్రిత్వ శాఖగా లాగిన్ అవ్వండి',

  'pillars.title': 'ప్లాట్‌ఫారమ్ ముఖ్య స్తంభాలు & లక్ష్యాలు',
  'pillars.subtitle': 'సహాయక సంస్థలలో సంపూర్ణ పారదర్శకత, లబ్ధిదారుల భద్రత మరియు చట్టబద్ధమైన సమ్మతి.',
  'pillars.cctv_badge': 'లైవ్ యాక్టివ్',
  'pillars.cctv_title': '24×7 లైవ్ సీసీటీవీ నిఘా',
  'pillars.cctv_desc': 'వృద్ధాశ్రమాలు మరియు పునరావాస కేంద్రాల నుండి సురక్షిత ప్రత్యక్ష ఫీడ్‌లు మరియు వ్యత్యాసాల గుర్తింపు హెచ్చరికలు.',
  'pillars.inspections_badge': 'ఆడిట్ సిద్ధం',
  'pillars.inspections_title': 'డిజిటల్ ఆన్-సైట్ తనిఖీలు',
  'pillars.inspections_desc': 'ప్రామాణిక ఫీల్డ్ ఆడిట్ చెక్‌లిస్ట్‌లు, జీపీఎస్ ఫోటో సాక్ష్యాలు మరియు డిజిటల్ తనిఖీ పత్రాలు.',
  'pillars.biometric_badge': 'కాగ్ సమ్మతి',
  'pillars.biometric_title': 'బయోమెట్రిక్ హాజరు ఆడిట్',
  'pillars.biometric_desc': 'ఆధార్-ధృవీకరించబడిన లబ్ధిదారుల లెక్కింపు మరియు పారదర్శక డిజిటల్ రికార్డులు.',

  'nav.key_modules': 'కీలక మాడ్యూల్స్',
  'nav.how_it_works': 'పనితీరు విధానం',
  'nav.surveillance_grid': 'నిఘా గ్రిడ్',
  'nav.cluster_status': 'క్లస్టర్ స్థితి',
  'nav.active_grid': 'క్రియాశీల & ధృవీకరించబడిన గ్రిడ్',
  'nav.system_support': 'సిస్టమ్ మద్దతు / సహాయం',
  'nav.operational': '99.99% క్రియాశీలం',

  'footer.ministry': 'సామాజిక న్యాయం మరియు సాధికారత మంత్రిత్వ శాఖ · భారత ప్రభుత్వం',
  'footer.subtitle': 'జాతీయ సంస్థాగత నిఘా & తనిఖీ గ్రిడ్',
  'footer.privacy': 'గోప్యతా విధానం',
  'footer.terms': 'నిబంధనలు & షరతులు',
  'footer.copyright': 'సామాజిక న్యాయం మరియు సాధికారత విభాగం, భారత ప్రభుత్వం. సర్వహక్కులు ప్రత్యేకించబడ్డాయి.',
  'footer.compliance': 'GIGW 3.0 & STQC ధృవీకృతం',
  'footer.node_status': 'NIC సార్వభౌమ గ్రిడ్ ఆన్‌లైన్',

  'auth.modal_title': 'ప్రభుత్వ పోర్టల్ ప్రామాణీకరణ',
  'auth.modal_subtitle': 'మీ ఆధారాలను నమోదు చేయండి లేదా పరీక్షించడానికి ముందే కాన్ఫిగర్ చేసిన ప్రభుత్వ పాత్రను ఎంచుకోండి.',
  'auth.tab_signin': 'పాత్ర వ్యక్తిత్వ లాగిన్',
  'auth.tab_credentials': 'అధికారిక ఆధారాలు',
  'auth.label_role': 'నియమించబడిన పాత్ర ప్రొఫైల్',
  'auth.label_email': 'అధికారిక NIC / ప్రభుత్వ ఇమెయిల్ ID',
  'auth.label_password': 'భద్రతా పాస్‌వర్డ్',
  'auth.remember_me': 'ఈ పరికరంలో సెషన్‌ను గుర్తుంచుకో',
  'auth.btn_login': 'ప్రామాణీకరించండి & గ్రిడ్‌ను యాక్సెస్ చేయండి',
  'auth.btn_authenticating': 'NIC ఆధారాలను ధృవీకరిస్తోంది...',
  'auth.test_persona_hint': 'తక్షణ 1-క్లిక్ మూల్యాంకనం కోసం పైన ఏదైనా పాత్రను ఎంచుకోండి',
  'auth.security_notice': 'IT చట్టం 2000 ప్రకారం అధీకృత ప్రభుత్వ ప్రవేశం మాత్రమే. అన్ని సెషన్‌లు క్రిప్టోగ్రాఫికల్‌గా లాగ్ చేయబడతాయి.',
  'auth.error_invalid': 'చెల్లని ఆధారాలు. దయచేసి అధీకృత ప్రభుత్వ పాత్రను ఎంచుకోండి.',

  'simulation.banner_title': 'సిమ్యులేషన్ / డెమో వాతావరణం',
  'simulation.banner_default': 'డెమో మోడ్‌లో నడుస్తోంది: సీసీటీవీ వీడియో స్ట్రీమ్‌లు, వెబ్‌ఆర్‌టీసీ కాన్ఫరెన్స్ మరియు హాజరు టెలిమెట్రీ ఎటువంటి చెల్లింపు మౌలిక సదుపాయాలు లేకుండా అనుకరించబడ్డాయి.',
  'simulation.ai_active': 'జెమిని 3.8 ఫ్లాష్ మరియు లీఫ్‌లెట్ క్రియాశీలం',
  'simulation.start': 'సిమ్యులేషన్ ప్రారంభించు',
  'simulation.stop': 'సిమ్యులేషన్ ఆపు',
  'simulation.reset': 'సిమ్యులేషన్ రీసెట్ చేయి',
  'simulation.running': 'సిమ్యులేషన్ నడుస్తోంది',
  'simulation.stopped': 'సిమ్యులేషన్ ఆపబడింది',
  'simulation.paused': 'సిమ్యులేషన్ పాజ్ చేయబడింది',
  'simulation.status': 'సిమ్యులేషన్ స్థితి',
  'simulation.detection_rate': 'స్వయంచాలక గుర్తింపు రేటు',
  'simulation.false_alarm': 'తప్పుడు అలారం వ్యత్యాసం',
  'simulation.intercept_time': 'వ్యత్యాసం గుర్తింపు సమయం',
  'simulation.ai_decision': 'AI నిర్ణయ మాత్రిక',
  'simulation.rf_spectrum': 'RF స్పెక్ట్రమ్ & టెలిమెట్రీ టెలిఫోనీ',
  'simulation.strategy': 'స్మార్ట్ స్కాన్ వ్యూహం',
  'simulation.strategy_desc': 'టెలిమెట్రీ వ్యత్యాసాల గుర్తింపు కోసం డైనమిక్ ఫ్రీక్వెన్సీ హోపింగ్ మరియు రీఇన్‌ఫోర్స్‌మెంట్ లెర్నింగ్',
  'simulation.ai_recommendation': 'AI సిఫార్సు',
  'simulation.ai_recommendation_desc': 'ప్రస్తుత నెట్‌వర్క్ టెలిమెట్రీ ఆధారంగా క్రమాంకనం చేయబడిన సరైన క్లస్టర్ స్కానింగ్ ఫ్రీక్వెన్సీ',
  'simulation.activity_log': 'సిమ్యులేషన్ కార్యాచరణ లాగ్',
  'simulation.telemetry_active': 'టెలిమెట్రీ స్ట్రీమ్‌లు సమకాలీకరించబడ్డాయి',
  'simulation.cctv_active': 'సీసీటీవీ సిమ్యులేషన్ క్రియాశీలం: GPU-త్వరిత HTML5 కాన్వాస్ ద్వారా లైవ్ RTSP స్ట్రీమ్‌లు రెండర్ చేయబడ్డాయి.',
  'simulation.sandbox_toggle': 'శాండ్‌బాక్స్ & టెలిఫోనీ సిమ్యులేషన్ మోడ్',
  'simulation.sandbox_desc': 'వాస్తవ నోటీసులు జారీ చేయకుండా సీసీటీవీ హార్ట్‌బీట్స్, VoIP కాల్స్ మరియు ఫీల్డ్ అధికారుల వాస్తవిక అనుకరణను అనుమతిస్తుంది.',

  'charts.algorithmic_scoring': 'అల్గారిథమిక్ స్కోరింగ్',
  'charts.active_portfolios': 'క్రియాశీల పోర్ట్‌ఫోలియోలు',
  'charts.projects_count': 'ప్రాజెక్టుల సంఖ్య',
  'charts.beneficiaries_count': 'లబ్ధిదారుల సంఖ్య',
  'charts.schemes_footer': 'పీఎం-అజయ్, స్మైల్, శ్రేయస్, NAPDDR మరియు సీనియర్ సిటిజన్ సంక్షేమ పథకాలతో కూడినది',
  'charts.count': 'కౌంట్',
  'charts.projects': 'ప్రాజెక్ట్‌లు',
  'charts.score': 'స్కోర్',
  'charts.risk_level': 'రిస్క్ స్థాయి',

  'dashboard.critical_entities_title': 'పర్యవేక్షణ అవసరమైన కీలక రిస్క్ సంస్థలు',
  'dashboard.critical_entities_desc': 'బయోమెట్రిక్ వ్యత్యాసం, సీసీటీవీ డౌన్‌టైమ్ లేదా పెండింగ్ ఆడిట్‌లతో గుర్తించబడిన సంస్థలు.',
  'dashboard.view_all_projects': 'అన్ని ప్రాజెక్ట్‌లను వీక్షించండి',
  'dashboard.view_role_report': 'పాత్ర-నిర్దిష్ట నివేదికను వీక్షించండి',
  'dashboard.dossier_id': 'డాసియర్ ID',
  'dashboard.scope_ngo': 'అధీకృత ఎన్జీఓ పరిధి: కేంద్రం #{id} · వ్యక్తిగత సంస్థ కొలమానాలు & ఆడిట్ ఫీడ్',
  'dashboard.scope_inspector': 'ఫీల్డ్ ఇన్‌స్పెక్టరేట్ పరిధి: {region}లో క్షేత్రస్థాయి ధృవీకరణలు & ఆకస్మిక VC',
  'dashboard.scope_district': 'జిల్లా పరిపాలన పరిధి: జిల్లా {district}, {state} రాష్ట్రం',
  'dashboard.scope_ministry': 'కార్యక్రమ డైరెక్టరేట్: కేంద్ర రంగం పీఎం-అజయ్, స్మైల్ & ఆదర్శ్ గ్రామ్ పర్యవేక్షణ',
  'dashboard.scope_super_admin': 'జాతీయ అపెక్స్ సెంట్రల్ మానిటరింగ్ సెల్: ఏకీకృత మాస్టర్ డేటాబేస్ పర్యవేక్షణ (అఖిల భారత)',
  'dashboard.stat_sub_projects': 'DoSJE ప్రాజెక్ట్‌లు',
  'dashboard.stat_sub_cctv': '24×7 లైవ్ ఫీడ్‌లు',
  'dashboard.stat_sub_inspections': 'ఆడిట్‌లు & తనిఖీలు',
  'dashboard.stat_sub_alerts': 'సమ్మతి రాడార్',
  'dashboard.gps_verified': 'జీపీఎస్ ధృవీకరించబడింది',

  'app.initializing': 'సత్య నిరీక్షక్ ప్రారంభించబడుతోంది...',
  'app.loading_sub': 'సురక్షిత పథకాలు మరియు టెలిమెట్రీ రిజిస్ట్రీలు లోడ్ అవుతున్నాయి.',
  'app.search_placeholder': 'ప్రాజెక్ట్‌లు, అధికారులు, సంస్థలు, జిల్లాల కోసం శోధించండి...',
  'app.unauthorized_title': 'యాక్సెస్ పరిమితం చేయబడింది',
  'app.unauthorized_desc': 'ఈ మాడ్యూల్‌ను వీక్షించడానికి మీ ప్రస్తుత పాత్రకు అనుమతి లేదు.',
  'app.back_to_dashboard': 'డాష్‌బోర్డ్‌కు తిరిగి వెళ్లండి',
  'app.language_changed': 'భాష విజయవంతంగా మార్చబడింది',
  'app.more_languages': 'మరిన్ని భారతీయ భాషలు (22+ భాషా డైరెక్టరీ)...',
  'app.select_language': 'భాషను ఎంచుకోండి',
}

full_te = { **existing['te'], **te_extra }
write_ts_file('te', 'Telugu', full_te)

# Marathi additions
mr_extra = {
  'hero.badge': 'भारत सरकार • सामाजिक न्याय आणि सक्षमीकरण मंत्रालय',
  'hero.title': 'सत्य निरीक्षक · राष्ट्रीय संस्थात्मक देखरेख आणि तपासणी कमांड ग्रिड',
  'hero.dept': 'सामाजिक न्याय आणि सक्षमीकरण विभाग (DoSJE)',
  'hero.desc': 'देशभरातील अनुदानित वृद्धाश्रम, नशामुक्ती केंद्रे आणि दिव्यांगजन पुनर्वसन संस्थांमध्ये २४×७ थेट सीसीटीव्ही देखरेख, बायोमेट्रिक उपस्थिती पडताळणी आणि प्रत्यक्ष फील्ड तपासणीचे केंद्रीय डिजिटल व्यासपीठ.',
  'hero.super_admin_title': 'सुपर ॲडमिन',
  'hero.super_admin_desc': 'संपूर्ण राष्ट्रीय ग्रिड नियंत्रण, वापरकर्ता भूमिका आणि ऑडिट कन्सोल',
  'hero.super_admin_login': 'सुपर ॲडमिन म्हणून लॉगिन करा',
  'hero.inspector_title': 'तपासणी अधिकारी',
  'hero.inspector_desc': 'अचानक व्हिडिओ कॉल, फील्ड पुरावे आणि ऑडिट अहवाल',
  'hero.inspector_login': 'इन्स्पेक्टर म्हणून लॉगिन करा',
  'hero.district_title': 'जिल्हा कल्याण प्रशासन',
  'hero.district_desc': 'प्रादेशिक विसंगती पुनरावलोकन आणि अनुदान पडताळणी',
  'hero.district_login': 'जिल्हा अधिकारी म्हणून लॉगिन करा',
  'hero.ministry_title': 'केंद्रीय मंत्रालय',
  'hero.ministry_desc': 'राष्ट्रीय ऑडिट, अंदाजपत्रक आणि कॅग मंजुरी',
  'hero.ministry_login': 'मंत्रालय म्हणून लॉगिन करा',

  'pillars.title': 'प्लॅटफॉर्मचे मुख्य स्तंभ आणि उद्दिष्टे',
  'pillars.subtitle': 'अनुदानित संस्थांमध्ये पूर्ण पारदर्शकता, लाभार्थी सुरक्षा आणि वैधानिक अनुपालन.',
  'pillars.cctv_badge': 'थेट सक्रिय',
  'pillars.cctv_title': '२४×७ थेट सीसीटीव्ही देखरेख',
  'pillars.cctv_desc': 'वृद्धाश्रम आणि नशामुक्ती केंद्रांमधून सुरक्षित थेट कॅमेरा फीड आणि विसंगती रडार अलर्ट.',
  'pillars.inspections_badge': 'ऑडिट सज्ज',
  'pillars.inspections_title': 'डिजिटल ऑन-साइट तपासणी',
  'pillars.inspections_desc': 'प्रमाणित फील्ड ऑडिट चेकलिस्ट, जीपीएस-टॅग केलेले फोटो पुरावे आणि डिजिटल तपासणी डॉसियर.',
  'pillars.biometric_badge': 'कॅग अनुपालन',
  'pillars.biometric_title': 'बायोमेट्रिक उपस्थिती ऑडिट',
  'pillars.biometric_desc': 'आधार-प्रमाणित लाभार्थी उपस्थिती मेळ आणि कॅग अनुपालन पारदर्शक डिजिटल रेकॉर्ड.',

  'nav.key_modules': 'प्रमुख मॉड्यूल्स',
  'nav.how_it_works': 'कार्यपद्धती',
  'nav.surveillance_grid': 'देखरेख ग्रिड',
  'nav.cluster_status': 'क्लस्टर स्थिती',
  'nav.active_grid': 'सक्रिय आणि पडताळलेले ग्रिड',
  'nav.system_support': 'प्रणाली सहाय्य / संपर्क',
  'nav.operational': '९९.९९% सक्रिय',

  'footer.ministry': 'सामाजिक न्याय आणि सक्षमीकरण मंत्रालय · भारत सरकार',
  'footer.subtitle': 'राष्ट्रीय संस्थात्मक देखरेख आणि तपासणी ग्रिड',
  'footer.privacy': 'गोपनीयता धोरण',
  'footer.terms': 'नियम आणि अटी',
  'footer.copyright': 'सामाजिक न्याय आणि सक्षमीकरण विभाग, भारत सरकार. सर्व हक्क राखीव.',
  'footer.compliance': 'GIGW ३.० आणि STQC प्रमाणित',
  'footer.node_status': 'एनआयसी सॉव्हेरिन ग्रिड ऑनलाइन',

  'auth.modal_title': 'शासकीय पोर्टल प्रमाणीकरण',
  'auth.modal_subtitle': 'तुमचे क्रेडेंशियल प्रविष्ट करा किंवा चाचणीसाठी पूर्व-कॉन्फिगर केलेली शासकीय भूमिका निवडा.',
  'auth.tab_signin': 'भूमिका व्यक्तिमत्व लॉगिन',
  'auth.tab_credentials': 'अधिकृत क्रेडेंशियल',
  'auth.label_role': 'नियुक्त पद प्रोफाइल',
  'auth.label_email': 'अधिकृत एनआयसी / शासकीय ईमेल आयडी',
  'auth.label_password': 'सुरक्षा पासवर्ड',
  'auth.remember_me': 'या डिव्हाइसवर सत्र लक्षात ठेवा',
  'auth.btn_login': 'प्रमाणित करा आणि ग्रिडमध्ये प्रवेश करा',
  'auth.btn_authenticating': 'एनआयसी क्रेडेंशियल पडताळत आहे...',
  'auth.test_persona_hint': 'त्वरित १-क्लिक मूल्यांकनासाठी वरील कोणतीही भूमिका निवडा',
  'auth.security_notice': 'आयटी कायदा २००० अंतर्गत केवळ अधिकृत शासकीय प्रवेश. सर्व सत्रे क्रिप्टोग्राफिकरीत्या नोंदवली जातात.',
  'auth.error_invalid': 'अवैध क्रेडेंशियल. कृपया अधिकृत शासकीय भूमिका निवडा.',

  'simulation.banner_title': 'सिम्युलेशन / डेमो वातावरण',
  'simulation.banner_default': 'डेमो मोडमध्ये कार्यरत: सीसीटीव्ही व्हिडिओ प्रवाह, वेबआरटीसी कॉन्फरन्स आणि उपस्थिती टेलिमेट्री विनामूल्य सिम्युलेट केली आहे.',
  'simulation.ai_active': 'जेमिनी ३.८ फ्लॅश आणि लीफलेट सक्रिय',
  'simulation.start': 'सिम्युलेशन सुरू करा',
  'simulation.stop': 'सिम्युलेशन थांबवा',
  'simulation.reset': 'सिम्युलेशन रीसेट करा',
  'simulation.running': 'सिम्युलेशन सुरू आहे',
  'simulation.stopped': 'सिम्युलेशन थांबवले आहे',
  'simulation.paused': 'सिम्युलेशन थांबवले आहे',
  'simulation.status': 'सिम्युलेशन स्थिती',
  'simulation.detection_rate': 'स्वयंचलित ओळख दर',
  'simulation.false_alarm': 'खोटे अलार्म प्रमाण',
  'simulation.intercept_time': 'विसंगती ओळख वेळ',
  'simulation.ai_decision': 'एआय निर्णय मॅट्रिक्स',
  'simulation.rf_spectrum': 'आरएफ स्पेक्ट्रम आणि टेलिमेट्री टेलिफोनी',
  'simulation.strategy': 'स्मार्ट स्कॅन रणनीती',
  'simulation.strategy_desc': 'टेलिमेट्री विसंगती ओळखीसाठी डायनॅमिक फ्रिक्वेन्सी हॉपिंग आणि रीइन्फोर्समेंट लर्निंग',
  'simulation.ai_recommendation': 'एआय शिफारस',
  'simulation.ai_recommendation_desc': 'सध्याच्या नेटवर्क टेलिमेट्रीवर आधारित अनुकूलित स्कॅनिंग वारंवारता',
  'simulation.activity_log': 'सिम्युलेशन क्रियाकलाप लॉग',
  'simulation.telemetry_active': 'टेलिमेट्री प्रवाह समक्रमित',
  'simulation.cctv_active': 'सीसीटीव्ही सिम्युलेशन सक्रिय: GPU-प्रवेगक HTML5 कॅनव्हासद्वारे थेट RTSP प्रवाह प्रदर्शित.',
  'simulation.sandbox_toggle': 'सँडबॉक्स आणि टेलिफोनी सिम्युलेशन मोड',
  'simulation.sandbox_desc': 'प्रत्यक्ष नोटीस जारी न करता सीसीटीव्ही हार्टबीट्स, व्हीओआयपी कॉल आणि फील्ड अधिकाऱ्यांचे वास्तववादी सिम्युलेशन अनुमती देते.',

  'charts.algorithmic_scoring': 'अल्गोरिदम स्कोअरिंग',
  'charts.active_portfolios': 'सक्रिय पोर्टफोलिओ',
  'charts.projects_count': 'प्रकल्प संख्या',
  'charts.beneficiaries_count': 'लाभार्थी संख्या',
  'charts.schemes_footer': 'पीएम-अजय, स्माइल, श्रेयस, NAPDDR आणि ज्येष्ठ नागरिक कल्याण योजनांचा समावेश',
  'charts.count': 'संख्या',
  'charts.projects': 'प्रकल्प',
  'charts.score': 'गुण',
  'charts.risk_level': 'जोखीम पातळी',

  'dashboard.critical_entities_title': 'देखरेखीसाठी गंभीर जोखमीच्या संस्था',
  'dashboard.critical_entities_desc': 'स्वयंचलित बायोमेट्रिक तफावत, सीसीटीव्ही डाउनटाइम किंवा प्रलंबित ऑडिट असलेल्या संस्था.',
  'dashboard.view_all_projects': 'सर्व प्रकल्प पहा',
  'dashboard.view_role_report': 'भूमिका-विशिष्ट अहवाल पहा',
  'dashboard.dossier_id': 'डॉसियर आयडी',
  'dashboard.scope_ngo': 'अधिकृत एनजीओ व्याप्ती: केंद्र #{id} · स्वतंत्र संस्था मेट्रिक्स आणि ऑडिट फीड',
  'dashboard.scope_inspector': 'फील्ड इन्स्पेक्टर व्याप्ती: {region} मध्ये प्रत्यक्ष पडताळणी आणि अचानक व्हीसी',
  'dashboard.scope_district': 'जिल्हा प्रशासन व्याप्ती: जिल्हा {district}, {state} राज्य',
  'dashboard.scope_ministry': 'कार्यक्रम संचालनालय: केंद्रीय क्षेत्र पीएम-अजय, स्माइल आणि आदर्श ग्राम देखरेख',
  'dashboard.scope_super_admin': 'राष्ट्रीय सर्वोच्च केंद्रीय देखरेख कक्ष: एकत्रित मास्टर डेटाबेस देखरेख (अखिल भारतीय)',
  'dashboard.stat_sub_projects': 'सामाजिक न्याय प्रकल्प',
  'dashboard.stat_sub_cctv': '२४×७ थेट फीड्स',
  'dashboard.stat_sub_inspections': 'ऑडिट आणि तपासणी',
  'dashboard.stat_sub_alerts': 'अनुपालन रडार',
  'dashboard.gps_verified': 'जीपीएस पडताळलेले',

  'app.initializing': 'सत्य निरीक्षक सुरू होत आहे...',
  'app.loading_sub': 'सुरक्षित योजना आणि टेलिमेट्री नोंदवही लोड होत आहे.',
  'app.search_placeholder': 'प्रकल्प, अधिकारी, संस्था, जिल्हे शोधा...',
  'app.unauthorized_title': 'प्रवेश प्रतिबंधित',
  'app.unauthorized_desc': 'तुमच्या सध्याच्या भूमिकेला हे मॉड्यूल पाहण्याची परवानगी नाही.',
  'app.back_to_dashboard': 'डॅशबोर्डवर परत जा',
  'app.language_changed': 'भाषा यशस्वीरीत्या बदलली',
  'app.more_languages': 'अधिक भारतीय भाषा (२२+ भाषा डिरेक्टरी)...',
  'app.select_language': 'भाषा निवडा',
}

full_mr = { **existing['mr'], **mr_extra }
write_ts_file('mr', 'Marathi', full_mr)

# Tamil additions
ta_extra = {
  'hero.badge': 'இந்திய அரசு • சமூக நீதி மற்றும் அதிகாரமளித்தல் அமைச்சகம்',
  'hero.title': 'சத்ய நிரக்ஷக் · தேசிய நிறுவன கண்காணிப்பு மற்றும் ஆய்வு கட்டளை கட்டமைப்பு',
  'hero.dept': 'சமூக நீதி மற்றும் அதிகாரமளித்தல் துறை (DoSJE)',
  'hero.desc': 'நாடு முழுவதும் உள்ள முதியோர் இல்லங்கள், போதை மறுவாழ்வு மையங்கள் மற்றும் நிறுவனங்களில் 24×7 நேரலை சிசிடிவி கண்காணிப்பு, பயோமெட்ரிக் வருகை மற்றும் கள ஆய்வுகளுக்கான மைய டிஜிட்டல் தளம்.',
  'hero.super_admin_title': 'முதன்மை நிர்வாகி',
  'hero.super_admin_desc': 'முழு தேசிய கட்டமைப்பு கட்டுப்பாடு, பயனர் பாத்திரங்கள் மற்றும் தணிக்கை பணியகம்',
  'hero.super_admin_login': 'முதன்மை நிர்வாகியாக உள்நுழைக',
  'hero.inspector_title': 'ஆய்வு அதிகாரிகள்',
  'hero.inspector_desc': 'திடீர் வீடியோ அழைப்புகள், கள ஆதாரங்கள் மற்றும் ஆய்வு அறிக்கைகள்',
  'hero.inspector_login': 'ஆய்வாளராக உள்நுழைக',
  'hero.district_title': 'மாவட்ட நல நிர்வாகம்',
  'hero.district_desc': 'பிராந்திய முரண்பாடுகள் மறுஆய்வு மற்றும் மானிய சரிபார்ப்புகள்',
  'hero.district_login': 'அதிகாரியாக உள்நுழைக',
  'hero.ministry_title': 'மத்திய அமைச்சகம்',
  'hero.ministry_desc': 'தேசிய தணிக்கை, வரவு செலவு திட்டம் மற்றும் சிஏஜி ஒப்புதல்',
  'hero.ministry_login': 'அமைச்சகமாக உள்நுழைக',

  'pillars.title': 'தளத்தின் முக்கிய தூண்கள் & நோக்கங்கள்',
  'pillars.subtitle': 'உதவிபெறும் நிறுவனங்களில் முழு வெளிப்படைத்தன்மை, பயனாளி பாதுகாப்பு மற்றும் சட்டப்பூர்வ இணக்கம்.',
  'pillars.cctv_badge': 'நேரலை செயலில்',
  'pillars.cctv_title': '24×7 நேரலை சிசிடிவி கண்காணிப்பு',
  'pillars.cctv_desc': 'நிறுவனங்களில் இருந்து பாதுகாப்பான நேரலை கேமரா ஸ்ட்ரீம்கள் மற்றும் தானியங்கி முரண்பாடு எச்சரிக்கைகள்.',
  'pillars.inspections_badge': 'தணிக்கை தயார்',
  'pillars.inspections_title': 'டிஜிட்டல் கள ஆய்வுகள்',
  'pillars.inspections_desc': 'நிலையான கள தணிக்கை சரிபார்ப்பு பட்டியல்கள், ஜிபிஎஸ் புகைப்பட சான்றுகள் மற்றும் டிஜிட்டல் ஆவணங்கள்.',
  'pillars.biometric_badge': 'சிஏஜி இணக்கமானது',
  'pillars.biometric_title': 'பயோமெட்ரிக் வருகை தணிக்கை',
  'pillars.biometric_desc': 'ஆதார் சரிபார்க்கப்பட்ட பயனாளிகள் வருகை சரிபார்ப்பு மற்றும் வெளிப்படையான டிஜிட்டல் பதிவுகள்.',

  'nav.key_modules': 'முக்கிய தொகுதிகள்',
  'nav.how_it_works': 'செயல்படும் விதம்',
  'nav.surveillance_grid': 'கண்காணிப்பு கட்டமைப்பு',
  'nav.cluster_status': 'தொகுப்பு நிலை',
  'nav.active_grid': 'செயலில் உள்ள சரிபார்க்கப்பட்ட கட்டமைப்பு',
  'nav.system_support': 'கணினி ஆதரவு / உதவி',
  'nav.operational': '99.99% செயல்பாட்டில்',

  'footer.ministry': 'சமூக நீதி மற்றும் அதிகாரமளித்தல் அமைச்சகம் · இந்திய அரசு',
  'footer.subtitle': 'தேசிய நிறுவன கண்காணிப்பு & ஆய்வு கட்டமைப்பு',
  'footer.privacy': 'தனியுரிமைக் கொள்கை',
  'footer.terms': 'விதிமுறைகள் மற்றும் நிபந்தனைகள்',
  'footer.copyright': 'சமூக நீதி மற்றும் அதிகாரமளித்தல் துறை, இந்திய அரசு. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
  'footer.compliance': 'GIGW 3.0 & STQC இணக்கமானது',
  'footer.node_status': 'NIC இறையாண்மை கட்டமைப்பு ஆன்லைனில் உள்ளது',

  'auth.modal_title': 'அரசு போர்டல் அங்கீகாரம்',
  'auth.modal_subtitle': 'உங்கள் சான்றுகளை உள்ளிடவும் அல்லது சோதிக்க முன்பே உள்ளமைக்கப்பட்ட அரசு பாத்திரத்தை தேர்வு செய்யவும்.',
  'auth.tab_signin': 'பாத்திர உள்நுழைவு',
  'auth.tab_credentials': 'அதிகாரப்பூர்வ சான்றுகள்',
  'auth.label_role': 'நியமிக்கப்பட்ட பாத்திர சுயவிவரம்',
  'auth.label_email': 'அதிகாரப்பூர்வ NIC / அரசு மின்னஞ்சல் முகவரி',
  'auth.label_password': 'பாதுகாப்பு கடவுச்சொல்',
  'auth.remember_me': 'இந்த சாதனத்தில் அமர்வை நினைவில் கொள்க',
  'auth.btn_login': 'அங்கீகரித்து தளத்தை அணுகவும்',
  'auth.btn_authenticating': 'சான்றுகள் சரிபார்க்கப்படுகின்றன...',
  'auth.test_persona_hint': 'உடனடி 1-கிளிக் மதிப்பீட்டிற்கு மேலே உள்ள ஏதேனும் பாத்திரத்தைத் தேர்ந்தெடுக்கவும்',
  'auth.security_notice': 'IT சட்டம் 2000 இன் கீழ் அங்கீகரிக்கப்பட்ட அணுகல் மட்டுமே. அனைத்து அமர்வுகளும் பதிவு செய்யப்படுகின்றன.',
  'auth.error_invalid': 'தவறான சான்றுகள். அங்கீகரிக்கப்பட்ட அரசு பாத்திரத்தைத் தேர்ந்தெடுக்கவும்.',

  'simulation.banner_title': 'உருவகப்படுத்துதல் / டெமோ சூழல்',
  'simulation.banner_default': 'டெமோ பயன்முறையில் இயங்குகிறது: சிசிடிவி வீடியோக்கள், வெப்ஆர்டிசி அழைப்புகள் மற்றும் வருகை தொலை அளவீடுகள் கட்டணமின்றி உருவகப்படுத்தப்பட்டுள்ளன.',
  'simulation.ai_active': 'ஜெமினி 3.8 ஃப்ளாஷ் & லீஃப்லெட் செயலில் உள்ளன',
  'simulation.start': 'உருவகப்படுத்துதலைத் தொடங்கு',
  'simulation.stop': 'உருவகப்படுத்துதலை நிறுத்து',
  'simulation.reset': 'மீட்டமைக்கவும்',
  'simulation.running': 'உருவகப்படுத்துதல் இயங்குகிறது',
  'simulation.stopped': 'உருவகப்படுத்துதல் நிறுத்தப்பட்டது',
  'simulation.paused': 'உருவகப்படுத்துதல் இடைநிறுத்தப்பட்டது',
  'simulation.status': 'உருவகப்படுத்துதல் நிலை',
  'simulation.detection_rate': 'தானியங்கி கண்டறிதல் விகிதம்',
  'simulation.false_alarm': 'தவறான எச்சரிக்கை விகிதம்',
  'simulation.intercept_time': 'முரண்பாடு கண்டறிதல் நேரம்',
  'simulation.ai_decision': 'AI முடிவு அணி',
  'simulation.rf_spectrum': 'RF அலைக்கற்றை & தொலை அளவீட்டு தொலைபேசி',
  'simulation.strategy': 'ஸ்மார்ட் ஸ்கேன் உத்தி',
  'simulation.strategy_desc': 'தொலை அளவீட்டு முரண்பாடுகளை கண்டறிவதற்கான மாறும் அலைவரிசை மாற்றம் மற்றும் வலுவூட்டல் கற்றல்',
  'simulation.ai_recommendation': 'AI பரிந்துரை',
  'simulation.ai_recommendation_desc': 'தற்போதைய நெட்வொர்க் நிலையின் அடிப்படையில் அளவீடு செய்யப்பட்ட உகந்த ஸ்கேனிங் அலைவரிசை',
  'simulation.activity_log': 'உருவகப்படுத்துதல் பதிவு',
  'simulation.telemetry_active': 'தொலை அளவீட்டு ஓட்டங்கள் ஒத்திசைக்கப்பட்டன',
  'simulation.cctv_active': 'சிசிடிவி உருவகப்படுத்துதல் செயலில் உள்ளது: HTML5 கேன்வாஸ் வழியாக நேரலை ஆர்டிஎஸ்பி ஸ்ட்ரீம்கள் வழங்கப்படுகின்றன.',
  'simulation.sandbox_toggle': 'சாண்ட்பாக்ஸ் & உருவகப்படுத்துதல் முறை',
  'simulation.sandbox_desc': 'அறிவிப்புகளை வழங்காமல் சிசிடிவி நிலைகள் மற்றும் கள அதிகாரிகளின் யதார்த்தமான உருவகப்படுத்துதலை அனுமதிக்கிறது.',

  'charts.algorithmic_scoring': 'அல்காரிதமிக் மதிப்பீடு',
  'charts.active_portfolios': 'செயலில் உள்ள திட்டங்கள்',
  'charts.projects_count': 'திட்டங்களின் எண்ணிக்கை',
  'charts.beneficiaries_count': 'பயனாளிகள் எண்ணிக்கை',
  'charts.schemes_footer': 'PM-AJAY, SMILE, SHREYAS, NAPDDR மற்றும் மூத்த குடிமக்கள் நலத்திட்டங்கள் உள்ளடங்கியவை',
  'charts.count': 'எண்ணிக்கை',
  'charts.projects': 'திட்டங்கள்',
  'charts.score': 'மதிப்பெண்',
  'charts.risk_level': 'ஆபத்து நிலை',

  'dashboard.critical_entities_title': 'கண்காணிப்பு தேவைப்படும் தீவிர ஆபத்துள்ள நிறுவனங்கள்',
  'dashboard.critical_entities_desc': 'பயோமெட்ரிக் முரண்பாடு, சிசிடிவி செயலிழப்பு அல்லது தாமதமான தணிக்கை கொண்ட நிறுவனங்கள்.',
  'dashboard.view_all_projects': 'அனைத்து திட்டங்களையும் காண்க',
  'dashboard.view_role_report': 'பாத்திர அறிக்கை பார்க்க',
  'dashboard.dossier_id': 'ஆவண ஐடி',
  'dashboard.scope_ngo': 'அங்கீகரிக்கப்பட்ட என்ஜிஓ வரம்பு: மையம் #{id} · தனிப்பட்ட அளவீடுகள் மற்றும் தணிக்கை தகவல்',
  'dashboard.scope_inspector': 'கள ஆய்வாளர் வரம்பு: {region} மண்டலத்தில் கள சரிபார்ப்புகள் மற்றும் திடீர் விசி',
  'dashboard.scope_district': 'மாவட்ட நிர்வாக வரம்பு: {district} மாவட்டம், {state} மாநிலம்',
  'dashboard.scope_ministry': 'திட்ட இயக்குநரகம்: மத்திய துறை PM-AJAY, SMILE & ஆதர்ஷ் கிராம கண்காணிப்பு',
  'dashboard.scope_super_admin': 'தேசிய முதன்மை மத்திய கண்காணிப்பு பிரிவு: ஒருங்கிணைந்த முதன்மை தரவுத்தள மேற்பார்வை (அனைத்திந்தியா)',
  'dashboard.stat_sub_projects': 'சமூக நீதி திட்டங்கள்',
  'dashboard.stat_sub_cctv': '24×7 நேரலை ஊட்டங்கள்',
  'dashboard.stat_sub_inspections': 'தணிக்கை & ஆய்வுகள்',
  'dashboard.stat_sub_alerts': 'இணக்க ரேடார்',
  'dashboard.gps_verified': 'ஜிபிஎஸ் சரிபார்க்கப்பட்டது',

  'app.initializing': 'சத்ய நிரக்ஷக் தொடங்குகிறது...',
  'app.loading_sub': 'பாதுகாப்பான திட்டங்கள் மற்றும் பதிவேடுகள் ஏற்றப்படுகின்றன.',
  'app.search_placeholder': 'திட்டங்கள், அதிகாரிகள், நிறுவனங்கள், மாவட்டங்களை தேடவும்...',
  'app.unauthorized_title': 'அணுகல் தடைசெய்யப்பட்டுள்ளது',
  'app.unauthorized_desc': 'இந்த தொகுதியைப் பார்க்க உங்கள் தற்போதைய பாத்திரத்திற்கு அனுமதியில்லை.',
  'app.back_to_dashboard': 'டாஷ்போர்டுக்குத் திரும்பு',
  'app.language_changed': 'மொழி வெற்றிகரமாக மாற்றப்பட்டது',
  'app.more_languages': 'மேலும் இந்திய மொழிகள் (22+ மொழிகள் அடைவு)...',
  'app.select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
}

full_ta = { **existing['ta'], **ta_extra }
write_ts_file('ta', 'Tamil', full_ta)

print("te, mr, ta completed.")
